name: Nix Update
on:
  workflow_dispatch:
  push:
    paths:
      - "go.sum"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for Updates
        run: nix run github:Mic92/nix-update -- composer-registry --url https://github.com/shyim/composer-registry --flake

      - name: Commit file
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update vendor sha"

      
